name: Dart CI

# Define when the workflow should run
on:
  push:
    branches: [main] # Run on push events to the main branch
  pull_request:
    branches: [main] # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Set the operating system for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the checkout action to get the repository's code

      # Install the Dart SDK
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1 # Use the setup-dart action to install the Dart SDK
        with:
          dart-sdk-version: '3.3.3' 
          # Specify the Dart SDK version to install

      - name: Install dependencies
        run: dart pub get # Run 'dart pub get' to install project dependencies

      # Uncomment this step to enforce code formatting
      # - name: Verify code formatting
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze # Run 'dart analyze' to perform static analysis on the Dart code

      - name: Run tests
        run: dart test # Run tests using 'dart test'

      # Optionally, you can add more steps here for deployment, publishing packages, etc.
